#!/usr/bin/env python3
"""Validate PubMed tool-calling augmentation files.

This is a cheap structural validator for the files generated by
`augment_tool_calling_data.py`. It intentionally validates only local schema and
tool-call invariants; it does not require a model, tokenizer, OpenWebUI, PubMed,
or network access.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = PROJECT_ROOT / "data" / "training-data"
TOOL_NAME = "deep_research_pubmed"


def iter_jsonl(path: Path) -> Iterable[tuple[int, dict[str, Any]]]:
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                yield line_number, json.loads(stripped)
            except json.JSONDecodeError as exc:
                raise AssertionError(f"{path}:{line_number}: invalid JSON: {exc}") from exc


def assert_tool_sft_row(path: Path, line_number: int, row: dict[str, Any]) -> None:
    messages = row.get("messages")
    if not isinstance(messages, list) or len(messages) < 5:
        raise AssertionError(f"{path}:{line_number}: expected messages list with at least 5 messages")

    roles = [message.get("role") for message in messages[:5]]
    if roles != ["system", "user", "assistant", "tool", "assistant"]:
        raise AssertionError(f"{path}:{line_number}: unexpected first roles: {roles}")

    assistant_call = messages[2]
    tool_calls = assistant_call.get("tool_calls")
    if not isinstance(tool_calls, list) or len(tool_calls) != 1:
        raise AssertionError(f"{path}:{line_number}: assistant turn must contain exactly one tool call")

    tool_call = tool_calls[0]
    function = tool_call.get("function") or {}
    if tool_call.get("type") != "function" or function.get("name") != TOOL_NAME:
        raise AssertionError(f"{path}:{line_number}: expected {TOOL_NAME} function tool call")

    call_id = tool_call.get("id")
    tool_message = messages[3]
    if not call_id or tool_message.get("tool_call_id") != call_id:
        raise AssertionError(f"{path}:{line_number}: tool_call_id does not match assistant call id")
    if tool_message.get("name") != TOOL_NAME:
        raise AssertionError(f"{path}:{line_number}: tool message name is not {TOOL_NAME}")

    try:
        args = json.loads(function.get("arguments") or "{}")
    except json.JSONDecodeError as exc:
        raise AssertionError(f"{path}:{line_number}: tool arguments are not valid JSON") from exc
    if not isinstance(args.get("query"), str) or not args["query"].strip():
        raise AssertionError(f"{path}:{line_number}: tool arguments must include a non-empty query")


def validate_sft(path: Path) -> int:
    count = 0
    for line_number, row in iter_jsonl(path):
        assert_tool_sft_row(path, line_number, row)
        count += 1
    return count


def validate_dpo(path: Path) -> int:
    count = 0
    for line_number, row in iter_jsonl(path):
        chosen = row.get("chosen")
        rejected = row.get("rejected")
        if not isinstance(chosen, list) or not isinstance(rejected, list):
            raise AssertionError(f"{path}:{line_number}: expected chosen and rejected message lists")
        assert_tool_sft_row(path, line_number, {"messages": chosen})
        rejected_roles = [message.get("role") for message in rejected]
        if rejected_roles[:3] != ["system", "user", "assistant"]:
            raise AssertionError(f"{path}:{line_number}: rejected side must be direct system/user/assistant")
        if any(message.get("tool_calls") for message in rejected):
            raise AssertionError(f"{path}:{line_number}: rejected side should not contain tool_calls")
        count += 1
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate generated PubMed tool-calling augmentation JSONL files.")
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    args = parser.parse_args()

    data_dir = args.data_dir.resolve()
    sft_path = data_dir / "pubmed_oncologist_v2_tool_sft_messages.jsonl"
    dpo_path = data_dir / "pubmed_oncologist_v2_tool_dpo_messages.jsonl"
    for path in [sft_path, dpo_path]:
        if not path.exists():
            raise FileNotFoundError(f"Missing expected file: {path}")

    sft_count = validate_sft(sft_path)
    dpo_count = validate_dpo(dpo_path)
    print("Validation passed.")
    print(f"  Tool SFT rows: {sft_count:,}")
    print(f"  Tool DPO rows: {dpo_count:,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())